package edu.srh.bikehire.dao;

public enum DAOType {
	BIKEDAO,
	BIKERENTMAPPINGDAO,
	BIKESTATUSDAO,
	BIKESTOCKDAO,
	BIKETYPEDAO,
	CURRENTORDERDAO,
	INVOICEDAO,
	ORDERHISTORYDAO,
	ORDERPAYMENTDAO,
	USERACCOUNTDAO,
	USERCREDENTIALDAO,
	USERDAO,
	WAREHOUSEDAO;
}
